### PR TITLE
Fix OB empty check during provisioning

### LINKED ISSUE #203: Fix provision check for empty OB returned
See discussion on comment: https://github.com/kube-object-storage/lib-bucket-provisioner/pull/201#discussion_r546008824

### PR DESCRIPTION
**Pull request by BlaineEXE**
Fix the existing check for an OB empty struct by using k8s api's semantic
deep-equality methods. Previously, this was a pointer equality check and
not a valid check for an empty struct. The k8s code generator does not
generate `==` or other equality methods for generated types that might
have been able to be used.

Signed-off-by: Blaine Gardner <blaine.gardner@redhat.com>

Fixes #203 

Ping @jeffvance to review without any rush.

Changes to go mod files are due to running `go mod tidy` after adding the new reference to a new k8s api machinery lib.

### CODE REVIEW

**Comment by jeffvance** [comment]
LGTM. Would you mind adding a comment as to why the generated `DeepEqual` and the golang `reflect.DeepEqual` cannot be used?

File: pkg/provisioner/controller.go [hunk 1]
```diff
@@ -400,7 +401,9 @@ func (c *obcController) handleProvisionClaim(key string, obc *v1alpha1.ObjectBuc
 		ob, err = c.provisioner.Grant(options)
 	}
 	// Record whether the provisioner returned an empty object bucket for error handling use later
-	emptyBucket := (ob == nil || ob == (&v1alpha1.ObjectBucket{}))
+	// The k8s code generator does not generate equality methods, and golang's native
+	// reflect.DeepEqual panics at unexported k8s struct fields, so must use apiequality lib.
```
Comment (jeffvance) [inline pkg/provisioner/controller.go:405]: +1
